import Head from 'next/head'
import ParticipateChallenges from '../components/ParticipateChallenges'
import Navbar from '../components/Navbar'
import ExploreChallenges from '../components/ExploreChallenges'
import Hackathons from '../components/Hackathons'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <ParticipateChallenges/>
      <ExploreChallenges/>
      <Hackathons/>
      
    </div>
  )
}
